from pathlib import Path
import os

cwd = os.getcwd()
folders = ['databases', 'genomes']
subfolders = ['prokka', 'virsorter', 'phispy', 'IS-elements']

_ = [Path(Path(cwd).parent, folder) for folder in folders]
_ = Path(cwd, 'output').mkdir(exist_ok=True)
_ = [Path(cwd, 'output', subfolder).mkdir(exist_ok=True) for subfolder in subfolders]


configfile: 'config.yaml'

rule all:
    input:
        "../scripts/VirSorter",
        "../databases/virsorter-data",
        "../databases/IS-database",

        expand("output/IS-elements/{genome}.txt" , genome=config['genomes']),
        expand("output/phispy/{genome}.tsv", genome=config['genomes']),
        expand("output/virsorter/{genome}", genome=config['genomes'])


rule install_virsorter:
    output:
        directory("../scripts/VirSorter")
    priority: 100
    shell:
        "cd ../scripts/; "
        "git clone https://github.com/simroux/VirSorter.git; "
        "cd ../scripts/VirSorter/Scripts; "
        "make clean; make; cd {cwd}"


rule virsorter_database:
    output:
        directory("../databases/virsorter-data")
    priority: 100
    shell:
        "cd ../databases; rm -rf *tar.gz*; "
        "wget https://zenodo.org/record/1168727/files/virsorter-data-v2.tar.gz; "
        "tar -xvzf virsorter-data*.tar.gz; cd {cwd}"


rule IS_database:
    output:
        directory("../databases/IS-database")
    conda:
        "../envs/seqkit.yaml"
    priority: 100
    shell:
        "cd ../databases/; rm -rf ISfinder-sequences; "
        "git clone https://github.com/thanhleviet/ISfinder-sequences; "
        "rm -rf IS-database; mkdir IS-database; cd IS-database; "
        "seqkit rmdup -s < ../ISfinder-sequences/IS.fna > IS.fna; "
        "rm -rf ../ISfinder-sequences; "
        "makeblastdb -in IS.fna -parse_seqids -dbtype nucl; "


cwd = Path.cwd()
yamls = list(Path(cwd, ".snakemake/conda/").glob('*yaml'))
for yaml in yamls:
    with open(yaml, 'r+') as f:
        if 'virsorter' in f.read():
            target = str(yaml.with_suffix(''))

rule virsorter_env:
    ouput=directory("{target}/etc")
    priority: 100
    shell: "cp -rf ../scripts/etc {target}"



rule IS_elements:
    input:
        database=rules.IS_database.output
    output:
        "output/IS-elements/{genome}.txt"
    conda:
        "../envs/seqkit.yaml"
    params:
        query="../genomes/{genome}.fasta",
        identity=config['IS_BLAST']['identity'],
        evalue=config['IS_BLAST']['evalue']
    shell:
        "blastn -db {input.database}/IS.fna -query {params.query} "
        "-perc_identity {params.identity} -evalue {params.evalue} "
        '-outfmt "6 qstart qend" > output/IS-elements/{wildcards.genome}.txt'

# If output exists the command shouldn't be running...
# If prokka already annotated genome it will give rise to error.
rule annotate:
    input:
        infile="../genomes/{genome}.fasta"
    output:
        "output/prokka/{genome}.gbk"
    params:
        outdir="output/prokka/{genome}",
        fname="{genome}"
    priority: 99
    conda:
        "../envs/prokka.yaml"
    shell:
        "prokka --usegenus --genus Caudovirales --force --kingdom Bacteria "
        "--outdir {params.outdir} {input.infile}; "
        "cp {params.outdir}/*.gbk "
        "output/prokka/{params.fname}.gbk; "
        # "rm -rf {params.outdir}"


rule phispy:
    input:
        infile="output/prokka/{genome}.gbk",
        pvogs="../databases/pVOGs.hmm"
    output:
        "output/phispy/{genome}.tsv"
    params:
        outdir="output/phispy/{genome}"
    conda:
        "../envs/phispy.yaml"
    shell:
        "PhiSpy.py {input.infile} "
        "--phmms {input.pvogs} -o {params.outdir}; "
        "cp {params.outdir}/prophage_coordinates.tsv output/phispy/{wildcards.genome}.tsv"


rule virsorter:
    input:
        infile="../genomes/{genome}.fasta",
        virsorter=rules.install_virsorter.output,
        database=rules.virsorter_database.output,
        env=rules.virsorter_env.ouput
    output:
        directory("output/virsorter/{genome}")
    conda:
        "../envs/virsorter.yaml"
    shell:
        "{input.virsorter}/wrapper_phage_contigs_sorter_iPlant.pl -f {input.infile} "
        "-db 1 --data-dir {input.database} "
        "--wdir {output}; "
